apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app-service
  template:
    metadata:
      labels:
        app: web-app-service
    spec:
      containers:
        - name: web-app-service
          image: REGISTRY_HOSTNAME/vocal-lamp-357106/IMAGE:GITHUB_SHA
          ports:
            - containerPort: 8080
