---
apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: default
  labels:
    app: web-app
spec:
  ports:
    - protocol: TCP
      port: 8080
  selector:
    app: web-app
  type: LoadBalancer
