---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: default
  labels:
    app: web-app-service
spec:
  ports:
    - protocol: TCP
      port: 8080
  selector:
    app: web-app-service
  type: LoadBalancer
